import frozen from './course-bare-links.json'

/**
 * Reviewed course links for bare numbers in catalog descriptions ("Prerequisite:
 * 240"). Generated by `npm run build:course-links` from a one-time human review;
 * see scripts/course-link-verdicts.ts for the judgement record.
 *
 * Keyed by course id AND a hash of the decoded description. The course id matters
 * because cross-listed courses share description text but resolve bare numbers to
 * their own subject ("or 108" is ECON 108 on eight different listings, but "140"
 * is EARTHSYS 140 only from some of them). The hash matters because a description
 * edited in a later catalog dump then has no entry, and its bare numbers render as
 * plain text. Guessing is never the fallback.
 */
type FrozenLinks = Record<string, Array<[offset: number, length: number, courseId: string]>>

const LINKS = frozen as unknown as FrozenLinks

/** FNV-1a 32-bit. Must stay identical to the build script's implementation. */
export function hashDescription(decoded: string): string {
    let h = 0x811c9dc5
    for (let i = 0; i < decoded.length; i++) {
        h ^= decoded.charCodeAt(i)
        h = Math.imul(h, 0x01000193)
    }
    return (h >>> 0).toString(16).padStart(8, '0')
}

/** Reviewed bare-number links for a description, as offset -> [length, courseId]. */
export function bareLinksFor(courseId: string, decoded: string): Map<number, [number, string]> {
    const entries = LINKS[`${courseId}:${hashDescription(decoded)}`]
    const map = new Map<number, [number, string]>()
    if (entries) for (const [offset, length, courseId] of entries) map.set(offset, [length, courseId])
    return map
}
